name: zarply
description: "ZARPLY Wallet"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://zarply.co.za
repository: https://gitea.cyber-mint.com/ZARPLY/zarply
issue_tracker: https://gitea.cyber-mint.com/ZARPLY/zarply/issues
documentation:
platforms:
  android:
  ios:

version: 1.0.2+20

environment:
  sdk: ^3.9.2
  flutter: ^3.38.4

dependencies:
  bip39: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^10.0.0
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.20.1
  mobile_scanner: ^7.1.3
  package_info_plus: ^9.0.0
  provider: ^6.1.2
  qr: ^3.0.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  solana: ^0.32.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7

flutter:
  uses-material-design: true

  # TODO: create assets/ folder in root dir
  # TODO: do not list all images here, use directories (assets/images/)
  # assets/images/
  assets:
    - images/saflag.png
    - images/zarp.png
    - images/solana.png
    - images/logo.png
    - images/splash.png
    - images/qr-code-logo.png
    - images/payed.png
    - images/received.png
    - .env.prod
    - .env.qa

  # TODO: ask a designer to provide fonts for our project and specify them here
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
